In [6]:
import pandas as pd

df = pd.read_excel('/Online Retail.xlsx')

print("Total rows:", len(df))
print("Total columns:", len(df.columns))

display(df.head())

Total rows: 541909
Total columns: 8

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 5268

In [9]:
before = len(df)

df = df.drop_duplicates()

after = len(df)

print("Rows before cleaning:", before)
print("Duplicate rows removed:", before - after)
print("Rows after cleaning:", after)

Rows before cleaning: 541909
Duplicate rows removed: 5268
Rows after cleaning: 536641

In [10]:
print(df.dtypes)

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [11]:
df["CustomerID"] = df["CustomerID"].astype("Int64")

print(df.dtypes)

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              Int64
Country                object
dtype: object

In [12]:
df["Description"] = df["Description"].fillna("Unknown product")

print("Missing descriptions:", df["Description"].isnull().sum())
print("Unknown product entries:", (df["Description"] == "Unknown product").sum())

Missing descriptions: 0
Unknown product entries: 1454

In [13]:
print("Zero quantity:", (df["Quantity"] == 0).sum())
print("Negative quantity:", (df["Quantity"] < 0).sum())
print("Zero or negative price:", (df["UnitPrice"] <= 0).sum())

display(df[["Quantity", "UnitPrice"]].describe())

Zero quantity: 0
Negative quantity: 10587
Zero or negative price: 2512

            Quantity      UnitPrice
count  536641.000000  536641.000000
mean        9.620029       4.632656
std       219.130156      97.233118
min    -80995.000000  -11062.060000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   38970.000000

In [14]:
before = len(df)

df = df[df["UnitPrice"] > 0].copy()

print("Rows before price cleaning:", before)
print("Invalid-price rows removed:", before - len(df))
print("Rows after price cleaning:", len(df))
print("Remaining invalid prices:", (df["UnitPrice"] <= 0).sum())

Rows before price cleaning: 536641
Invalid-price rows removed: 2512
Rows after price cleaning: 534129
Remaining invalid prices: 0

In [15]:
# Calculate transaction value
df["TransactionAmount"] = df["Quantity"] * df["UnitPrice"]

# Extract date features
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["DayOfWeek"] = df["InvoiceDate"].dt.day_name()

# Identify cancellations and returns
df["IsCancellation"] = df["InvoiceNo"].astype(str).str.startswith("C")
df["IsReturnQuantity"] = df["Quantity"] < 0

display(df.head())

print("Total rows:", len(df))
print("Total columns:", len(df.columns))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TransactionAmount,Year,Month,DayOfWeek,IsCancellation,IsReturnQuantity
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,Wednesday,False,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,Wednesday,False,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,Wednesday,False,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,Wednesday,False,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,Wednesday,False,False

Total rows: 534129
Total columns: 14

In [16]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nInvalid prices:", (df["UnitPrice"] <= 0).sum())

Rows: 534129
Columns: 14

Missing values:
InvoiceNo                 0
StockCode                 0
Description               0
Quantity                  0
InvoiceDate               0
UnitPrice                 0
CustomerID           132565
Country                   0
TransactionAmount         0
Year                      0
Month                     0
DayOfWeek                 0
IsCancellation            0
IsReturnQuantity          0
dtype: int64

Duplicate rows: 0

Invalid prices: 0

In [17]:
df.to_csv("/content/cleaned_online_retail.csv", index=False)

print("Dataset saved successfully!")
print("File: cleaned_online_retail.csv")

Dataset saved successfully!
File: cleaned_online_retail.csv

In [18]:
from google.colab import files

files.download("/content/cleaned_online_retail.csv")